language: php

dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
