language: php

dist: trusty

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: ILLUMINATE_VERSION=5.8.*
    - php: 7.2
      env: ILLUMINATE_VERSION=6.*
    - php: 7.2
      env: ILLUMINATE_VERSION=7.*
    - php: 7.3
      env: ILLUMINATE_VERSION=6.*
    - php: 7.3
      env: ILLUMINATE_VERSION=7.*
    - php: 7.4
      env: ILLUMINATE_VERSION=6.*
    - php: 7.4
      env: ILLUMINATE_VERSION=7.*

before_script:
  - travis_retry composer self-update
  - travis_retry composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update
  - travis_retry composer update --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
